#ifndef APP_ONEWIRE_CONFIG_H
#define APP_ONEWIRE_CONFIG_H

#include <stdint.h>

#define APP_ONEWIRE_ROLE_MASTER                 1U
#define APP_ONEWIRE_ROLE_SLAVE                  2U

#ifndef APP_ONEWIRE_ROLE
#error "APP_ONEWIRE_ROLE must be defined as APP_ONEWIRE_ROLE_MASTER or APP_ONEWIRE_ROLE_SLAVE"
#endif

#if ((APP_ONEWIRE_ROLE != APP_ONEWIRE_ROLE_MASTER) && \
     (APP_ONEWIRE_ROLE != APP_ONEWIRE_ROLE_SLAVE))
#error "APP_ONEWIRE_ROLE has an invalid value"
#endif

#define APP_ONEWIRE_FRAME_HEADER               0xAAU
#define APP_ONEWIRE_MAX_DATA_LEN               32U
#define APP_ONEWIRE_FRAME_OVERHEAD             5U
#define APP_ONEWIRE_MAX_FRAME_LEN              \
    (APP_ONEWIRE_MAX_DATA_LEN + APP_ONEWIRE_FRAME_OVERHEAD)

#define APP_ONEWIRE_INTERBYTE_TIMEOUT_MS       5U

#define APP_ONEWIRE_HANDSHAKE_TOTAL_MS          500U
#define APP_ONEWIRE_HANDSHAKE_RESPONSE_MS       100U
#define APP_ONEWIRE_OPERATION_RESPONSE_MS       100U
#define APP_ONEWIRE_TX_COMPLETE_TIMEOUT_MS      100U
#define APP_ONEWIRE_MASTER_LINK_VALID_MS        450U
#define APP_ONEWIRE_MASTER_GUARD_MS               3U
#define APP_ONEWIRE_SLAVE_FAULT_MS              500U
#define APP_ONEWIRE_RESPONSE_TURNAROUND_MS        2U

#define APP_ONEWIRE_OPERATION_REHANDSHAKE        0x01U
#define APP_ONEWIRE_OPERATION_WRITE             0x03U
#define APP_ONEWIRE_OPERATION_READ              0x06U

#define APP_ONEWIRE_UART_RX_RING_SIZE           256U

#define APP_ONEWIRE_LOCAL_ADDR_MASTER          0x01U
#define APP_ONEWIRE_LOCAL_ADDR_SLAVE           0x02U

#define APP_ONEWIRE_REGISTER_MAX_ADDR          0x0100U

#endif
